## Задание на повторение материала
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [17]:
import numpy as np

a = np.arange(12, 24)
print (a)

[12 13 14 15 16 17 18 19 20 21 22 23]


Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [18]:
b1 = a.reshape(3, 4)
print(b1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
b2 = a.reshape(2, 6)
print(b2)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [20]:
b3 = a.reshape(4, 3)
print(b3)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [21]:
b4 = a.reshape(6, 2)
print(b4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [22]:
b5 = a.reshape(12, 1)
print(b5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [25]:
print ("Да. Одномерный массив представляет собой совокупность однотипных элементов, доступ к которым определяется одним индексом:")

print ("Проверяем второй элемент:", b5[1])
print ("Проверяем последний элемент:", b5[11])

Да. Одномерный массив представляет собой совокупность однотипных элементов, доступ к которым определяется одним индексом:
Проверяем второй элемент: [13]
Проверяем последний элемент: [23]


Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [26]:
с = np.random.randn(3, 4)

print(с)

[[-0.37529517  0.20402453 -0.68459322 -1.16170152]
 [ 0.6138917   0.82738761  2.42781866 -0.2100355 ]
 [ 0.17016032 -1.55703042 -0.04012543 -0.57943645]]


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [43]:
ar1 = np.arange(20, 0, -2)

print(ar1)

[20 18 16 14 12 10  8  6  4  2]


Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [45]:
ar2 = ar1.reshape(10, 1)

print(ar2)

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [52]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.concatenate((a, b), axis=0)

print(v.size)

10


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [65]:
a = np.arange (0, 12)

A = a.reshape (4, 3)
print (A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [66]:
At = np.transpose(A)
print (At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [70]:
B = A.dot(At)
print ("Размер матрицы B - 4x4")
print (B)

Размер матрицы B - 4x4
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [71]:
d = np.linalg.det(B)

print(d)

print ("Нельзя посчитать обратную матрицу, так как B - квадратная матрица, но ее определитель равен нулю")

0.0
Нельзя посчитать обратную матрицу, так как B - квадратная матрица, но ее определитель равен нулю


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [58]:
c = np.arange (0, 16)
print (c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [63]:
C = c.reshape(4, 4)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.
